@baseUrl = http://localhost:3000/

### pelne zapytanie
GET http://localhost:3000
Accept: application/json

### zapytanie skrócone
GET {{baseUrl}}
Accept: application/json

# NOWE ZAPYTANIA

### zapytanie pod house
GET {{baseUrl}}/house
Accept: application/json

### zapytanie pod house
GET {{baseUrl}}/house/room
Accept: application/json

### zapytanie pod garden bez middleware
GET {{baseUrl}}/graden
Accept: application/json


### filtrowanie gier po roku i platformie
GET {{baseUrl}}/games?year=1984&platform=Atari



### użycie metody POST
POST {{baseUrl}}/games/s
Content-Type: application/json

{
  "title": "Dom",
  "year": 1993,
  "platform": "PC",
  "genre": "Shooter"
}

### użycie metody POST z błędem
POST {{baseUrl}}/games/s
Content-Type: application/json

{
  "title": "Dom",
  "year": 1993,
  "genre": "Shooter"
}


### aktualizacja gry metodą PUT
# zmiana title i year
PUT {{baseUrl}}/games/1
Content-Type: application/json

{
  "title": "Mariusz po POLSKU",
  "year": 3987,
  "platform": "NES",
  "genre": "Platform"
}

### pytamy o grę z indeksem 1
GET {{baseUrl}}/games/1
Accept: application/json

### zapytanie, które zniszczy grę id=2
# chcieliśmy zamienić tytuł na same duże litery
PUT {{baseUrl}}/games/2
Content-Type: application/json

{
  "title": "PONG"
}

### sprawdzamy grę id=2
GET {{baseUrl}}/games/2
Accept: application/json



### Metoda Patch gra id=3
# zamienimy year na 3984
PATCH {{baseUrl}}/games/3
Content-Type: application/json

{
  "year":3983
}

### sprawdzamy poprawność zapytania o grę id=3
GET {{baseUrl}}/games/3
Accept: application/json

### Metoda Patch z niepoprawnym id=9999
PATCH {{baseUrl}}/games/9999
Content-Type: application/json

{
  "year":3984
}

### przed skasowanie id=4
GET {{baseUrl}}/games/4
Accept: application/json

### delete id=4
DELETE {{baseUrl}}/games/4
